name: compound
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:

  # firebase_auth:
  # cloud_firestore:
  # firebase_storage:
  firebase_messaging: ^7.0.3
  firebase_analytics:
  firebase_core: 
  firebase_dynamic_links: ^0.6.3
  # firebase_in_app_messaging: 
  firebase_crashlytics: 
  firebase_performance: 

  page_transition: "^1.1.5"
  http:
  #Check
  async:
  get_it:
  provider:
  provider_architecture: 1.0.6
  image_picker:
  cached_network_image:
  google_tag_manager: ^0.0.3
  dio: 3.0.9
  shared_preferences: 0.5.12+4
  logger: 0.8.3
  fimber: 0.4.0
  location: ^2.5.0
  google_maps_flutter: ^1.0.6
  # google_maps_place_picker: ^1.0.1
  carousel_slider: 3.0.0
  intl_phone_number_input: ^0.4.6+2
  pin_code_text_field: ^1.2.1
  url_launcher: ^5.4.2
  percent_indicator: "^2.1.1"
  flutter_svg: 0.19.0
  flutter_rating_bar: ^3.0.1+1
  sliver_fab: 1.0.0
  international_phone_input: 1.0.4
  intl:
  pull_to_refresh: 1.6.3
  photo_view: 0.10.2
  get: 3.22.2
  package_info: 0.4.3+2
  intro_slider: 2.3.3
  share: 0.6.5+4
  rate_my_app: 0.7.2
  rating_dialog: ^1.0.0
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  google_api_headers: ">=0.1.0 <1.0.0"
  google_maps_webservice: ^0.0.19
  tuple: ^1.0.3
  overlay_support: ^1.0.5
  font_awesome_flutter: 8.11.0
  # catcher: 0.4.2
  data_connection_checker: ^0.3.4
  sign_in_with_apple: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dzor_logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 600
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300