name: compound
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  page_transition: "^1.1.5"
  http:
  #Check
  async:
  get_it:
  provider:
  provider_architecture:
  # firebase_auth:
  # cloud_firestore:
  # firebase_storage:
  image_picker:
  cached_network_image:
  firebase_messaging: ^7.0.3
  firebase_analytics:
  dio: 3.0.9
  shared_preferences: 0.5.6+2
  logger: 0.8.3
  fimber: 0.4.0
  location: ^2.5.0
  google_maps_flutter: ^0.5.11
  google_maps_place_picker: 0.9.4
  carousel_slider: ^1.3.1
  intl_phone_number_input: ^0.4.6+2
  pin_code_text_field: ^1.2.1
  url_launcher: ^5.4.2
  percent_indicator: "^2.1.1"
  flutter_svg: 0.18.0
  flutter_rating_bar: ^3.0.1+1
  international_phone_input: ^1.0.4
  intl:
  pull_to_refresh: ^1.6.1
  photo_view: ^0.10.2
  get: ^3.22.2
  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/DZOR_full_logo_verti.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/title.png
    - assets/images/icon_large.png
    - assets/images/logo_red.png
    - assets/images/DZOR_full_logo.png
    - assets/images/tile_ui_placeholder.jpg
    - assets/images/placeholder.png
    - assets/images/coupon_1.svg
    - assets/images/cash_icon.png
    - assets/images/gpay_icon.png
    - assets/images/empty_cart.png
    - assets/images/paytm_icon.png
    - assets/images/phonepe_icon.png
    - assets/svg/DZOR_full_logo_verti.svg
    - assets/svg/logo.svg
    - assets/svg/ribbon.svg
    - assets/svg/discount.svg
    - assets/svg/wishlist.svg
    - assets/svg/tumblr-badge.svg
    - assets/svg/crease.svg
    - assets/svg/dressmaker.svg
    - assets/svg/fabric.svg
    - assets/svg/online.svg
    - assets/svg/bag.svg
    - assets/icons/info.png
    - assets/icons/filter.png
    - assets/icons/like.png
    - assets/icons/like.png
    - assets/icons/menu.png
    - assets/icons/shopping-cart.png
    - assets/icons/address.svg
    - assets/icons/share.svg
    - assets/icons/DZOR_full_logo_verti.png
    - assets/icons/map.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 600
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
